### ISSUE TITLE
Stop Script

### ISSUE THREAD

**Issue by mjack24** [Johnson468/Stay-Awake#1]
How do I get this to stop after starting it?

**Comment by joseph-lister** [comment]
ctrl + C will stop the python script running

**Comment by ojoksimovic** [comment]
press the shift key.

**Comment by GavinChris7** [comment]
not working

**Comment by GavinChris7** [comment]
when run pycharm

**Comment by AntonioJPE** [comment]
> ctrl + C will stop the python script running

If the issue is solved we can close it, no?

**Comment by joseph-lister** [comment]
Yes please close Sent from my iPhoneOn 27 Mar 2023, at 22:40, AntonioJPE ***@***.***> wrote:﻿

ctrl + C will stop the python script running

If the issue is solved we can close it, no?
